version: '3'

services:
  dorc:
    image: dorc
    container_name: orc
    env_file: 
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 main.py
    networks:
      - services
networks:
  services:
    external:
      true
